ingress-nginx:
  service:
#  annotations:
#    metallb.universe.tf/loadBalancerIPs: "192.168.20.199"
#    type: LoadBalancer
#    loadBalancerIP: "192.168.20.199"
  controller:
#    kind: DaemonSet
    service:
      type: LoadBalancer
#      loadBalancerIP: "192.168.20.199"
      annotations:
        metallb.universe.tf/loadBalancerIPs: "192.168.20.199"
        type: LoadBalancer
    admissionWebhooks:
      timeoutSeconds: 30
#    metrics:
#      enabled: true
#      serviceMonitor:
#        enabled: true
#  tcp:
#    22: gitea/gitea-ssh:22 # TODO
