ingress-nginx:
  service:
  controller:
#    kind: DaemonSet
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: "192.168.20.199"
        type: LoadBalancer
    admissionWebhooks:
      timeoutSeconds: 30
#    metrics:
#      enabled: true
#      serviceMonitor:
#        enabled: true
#  tcp:
#    22: gitea/gitea-ssh:22 # TODO
