apiVersion: v1
kind: Service
metadata:
  name: openfaas-figlet
  namespace: open-faas
  labels:
    app: openfaas-figlet
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31111
  selector:
    app: openfaas-figlet
