---
apiVersion: v1
kind: Namespace
metadata:
  name: open-faas
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfaas-figlet
  namespace: open-faas
  labels:
   app: openfaas-figlet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfaas-figlet
  template:
    metadata:
      labels:
        app: openfaas-figlet
    spec:
      containers:
      - name: openfaas-figlet
        image: functions/figlet:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
