#!/bin/bash
TEMPL_NAME="ubuntu2204-cloud"
VMID="9003"
MEM="1024"
DISK_SIZE="32G"
DISK_STOR="local-zfs"
NET_BRIDGE="vmbr0"
SRC_IMG="https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
IMG_NAME="jammy-server-cloudimg-amd64.img"
wget -O $IMG_NAME $SRC_IMG
virt-customize --install qemu-guest-agent -a $IMG_NAME
virt-customize -a $IMG_NAME --run-command "truncate -s 0 /etc/machine-id"
qm create $VMID --name $TEMPL_NAME --memory $MEM --net0 virtio,bridge=$NET_BRIDGE
qm importdisk $VMID $IMG_NAME $DISK_STOR
qm set $VMID --scsihw virtio-scsi-pci --scsi0 $DISK_STOR:vm-$VMID-disk-0
qm set $VMID --ide2 $DISK_STOR:cloudinit
qm set $VMID --boot c --bootdisk scsi0
qm set $VMID --serial0 socket --vga serial0
qm set $VMID --ipconfig0 ip=dhcp
qm set $VMID --ciuser proxmox
qm set $VMID --cipassword proxmox
qm set $VMID --agent enabled=1
qm resize $VMID scsi0 $DISK_SIZE
qm template $VMID
rm $IMG_NAME
