#!/bin/sh

helm template \
    --include-crds \
    --namespace argocd \
    --atomic \
    argocd . \
    | kubectl apply -n argocd -f -
echo
echo
echo "Wait"
echo
echo
kubectl -n argocd wait --timeout=60s --for condition=Established \
       crd/applications.argoproj.io \
       crd/applicationsets.argoproj.io
